name: Chacke
on: push
jobs:
    init:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: InstallDeps
              run: npm ci
            - name: ConsoleLog
              run: echo "HELLO RUNER1"
